### ISSUE TITLE
有点问题想问

### ISSUE THREAD

**Issue by freelf** [cuzv/TinyCoordinator#1]
func populateData(with data: TCDataType, forReusableCell cell: TCCellType)
这个函数为什么放在TCDataSourceable中？为cell设置数据在cell的数据源方法中就可以设置了啊，放在TCDataSourceable这个协议中，每次创建一个新的datasource都需要去实现这个方法，为cell设置数据也可以抽出来，没必要每次都写啊

**Comment by cuzv** [comment]
怎么抽取出来啊？你并不知道使用者使用什么方式去给 cell 设置数据呢。

**Comment by freelf** [comment]
数据类型不是都抽象成TCDataType了么？而且一般cell知道自己需要什么类型的数据，直接过去转一下不行么？

**Comment by freelf** [comment]
![image](https://user-images.githubusercontent.com/15242207/40668147-5969ccb4-6396-11e8-98bd-61acf4f3a3ab.png)
不抽出来的话，所有的datasource岂不是都要重复这行代码

**Comment by cuzv** [comment]
如果是直接在自己项目里面的话，强制 cell 全部实现 `populate(data:)` 那么直接写死在库里面没问题。如果你非要纠结这个地方的话，完全可以写个默认实现给 `TCDataSource`，不存在重复的情况。抽取成库的目的更多的考虑到灵活性。

```Swift
extension TCDataSource {
    func populateData(with data: TCDataType, forReusableCell cell: TCCellType) {
        if let reusableCell = cell as? TCReusableViewSupport {
            reusableCell.populate(data: data)
        }
    }
}
```

**Comment by freelf** [comment]
多谢回答，确实实现一个默认实现比较好。
